[project]
name = "search-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.14",
    "pydantic-settings>=2.10.1",
    "python-multipart>=0.0.20",
    "typesense>=1.1.1",
    "uvicorn>=0.35.0",
]
